### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by denghejun** [walkmod/walkmod-checkstyle-plugin#9]
I just create an empty spring boot application base maven and simply execute below steps under project root directory, this is my demo project: https://github.com/denghejun/demo

```
walkmod add checkstyle
walkmod apply
```

**Walkmod Version**
```
--------------------------------------------------------------------------------
                     _    _       _ _   ___  ___          _                     
                    | |  | |     | | |  |  \/  |         | |                    
                    | |  | | __ _| | | _| .  . | ___   __| |                    
                    | |/\| |/ _` | | |/ / |\/| |/ _ \ / _` |                    
                    \  /\  / (_| | |   <| |  | | (_) | (_| |                    
                     \/  \/ \__,_|_|_|\_\_|  |_/\___/ \__,_|                    
--------------------------------------------------------------------------------
An open source tool to apply code conventions
version 3.0 - February 2017 -
--------------------------------------------------------------------------------
Walkmod version "3.0"
Java version: 11.0.2
Java Home: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
OS: Mac OS X, Version: 10.13.6
```

**ERROR INFO**
```
ERROR [main] - TRANSFORMATION CHAIN (default) FAILS
An exeception has been produced during the null transformation - org.walkmod.util.location.LocationImpl@43fda8d9
        at org.walkmod.maven.providers.MavenProject.resolveClassLoader(MavenProject.java:373)
        at org.walkmod.maven.providers.ClassLoaderConfigurationProvider.load(ClassLoaderConfigurationProvider.java:85)
        at org.walkmod.javalang.walkers.DefaultClasspathEvaluator.runClassLoaderInitializers(DefaultClasspathEvaluator.java:59)
        at org.walkmod.javalang.walkers.DefaultClasspathEvaluator.evaluate(DefaultClasspathEvaluator.java:21)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.calculateClasspath(DefaultJavaWalker.java:147)
        at org.walkmod.javalang.walkers.DefaultJavaWalker.execute(DefaultJavaWalker.java:161)
        at org.walkmod.impl.DefaultChainWalkerInvocation.invoke(DefaultChainWalkerInvocation.java:41)
        at org.walkmod.impl.DefaultChainInvocation.invoke(DefaultChainInvocation.java:38)
        at org.walkmod.impl.DefaultChainAdapter.execute(DefaultChainAdapter.java:166)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.executeAllChains(ConfigurationImpl.java:607)
        at org.walkmod.conf.entities.impl.ConfigurationImpl.execute(ConfigurationImpl.java:822)
        at org.walkmod.WalkModFacade.run(WalkModFacade.java:284)
        at org.walkmod.WalkModFacade.apply(WalkModFacade.java:142)
        at org.walkmod.commands.ApplyCommand.execute(ApplyCommand.java:40)
        at org.walkmod.WalkModDispatcher.execute(WalkModDispatcher.java:172)
        at org.walkmod.WalkModDispatcher.main(WalkModDispatcher.java:197)
Caused by: org.walkmod.conf.ConfigurationException
        ... 16 more
Caused by: java.lang.NullPointerException
        ... 16 more
```

**walkmod.xml**
```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd">
<walkmod>
    <transformation type="checkstyle"/>
</walkmod>
```

**Comment by yagee-de** [comment]
same here
